/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_dell_growup_NativeRenderer */

#ifndef _Included_com_example_dell_growup_NativeRenderer
#define _Included_com_example_dell_growup_NativeRenderer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_dell_growup_NativeRenderer
 * Method:    nativeOnStart
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_dell_growup_NativeRenderer_nativeOnStart(JNIEnv *, jclass);

JNIEXPORT void JNICALL Java_com_example_dell_growup_NativeRenderer_nativeSetAssetManager(JNIEnv *,jobject, jobject);

JNIEXPORT void JNICALL Java_com_example_dell_growup_NativeRenderer_nativeOnSurfaceCreated(JNIEnv *,jobject, int with, int height);

JNIEXPORT void JNICALL Java_com_example_dell_growup_NativeRenderer_nativeOnRender(JNIEnv * , jobject );

JNIEXPORT void JNICALL Java_com_example_dell_growup_NativeRenderer_nativeOnPause(JNIEnv * , jobject);

JNIEXPORT void JNICALL Java_com_example_dell_growup_NativeRenderer_nativeOnResume(JNIEnv * , jobject);

JNIEXPORT void JNICALL Java_com_example_dell_growup_NativeRenderer_nativeOnDestroy(JNIEnv * , jobject);

#ifdef __cplusplus
}
#endif
#endif
